name: beautify_partner
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_crashlytics: ^5.0.0
  google_sign_in: ^6.1.4
  bloc: ^9.0.0
  get: ^4.7.2
  get_it: ^8.0.3
  talker_bloc_logger: ^4.9.0
  talker_flutter: ^4.9.0
  shared_preferences: ^2.5.2
  permission_handler: ^11.3.1
  wakelock_plus: ^1.2.10
  injectable: ^2.5.0
  intl: ^0.20.2
  fluttertoast: ^8.2.12
  flutter_svg: ^2.2.0
  cloud_firestore: ^6.0.0
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^8.0.0
  change_app_package_name: ^1.4.0


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/svgs/


